version: '3.4'

services:
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:management # Koristimo RabbitMQ Docker sliku s uključenim upravljačkim sučeljem
    ports:
    - "5672:5672" # RabbitMQ working port
    - "15672:15672" # RabbitMQ control
    environment:
        RABBITMQ_DEFAULT_USER: rabbitmq
        RABBITMQ_DEFAULT_PASS: rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: MsSqlServer
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Password_01
    ports:
     - "1433:1433"

  redis:
    container_name: Redis
    image: redis:latest
    ports:
      - "6379:6379"

  accountservice:
    container_name: AccountService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
    ports:
      - "8082"

  characterservice:
    container_name: CharacterService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
    ports:
      - "8081"


  combatservice:
    container_name: CombatService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8083
    ports:
      - "8083"

