version: '3.4'

services:
  accountservice:
    image: ${DOCKER_REGISTRY-}accountservice
    build:
      context: .
      dockerfile: AccountService/Dockerfile

  characterservice:
    image: ${DOCKER_REGISTRY-}characterservice
    build:
      context: .
      dockerfile: CharacterService/Dockerfile


  combatservice:
    image: ${DOCKER_REGISTRY-}combatservice
    build:
      context: .
      dockerfile: CombatService/Dockerfile

